#ifndef STEINWURF_VERIFY_BACKENDS_STUB_HPP
#define STEINWURF_VERIFY_BACKENDS_STUB_HPP

#include "../verify_variadic_macro.hpp"

#define VERIFY_IMPL(...) VERIFY_VFUNC(VERIFY_IMPL, __VA_ARGS__)
#define VERIFY_DEBUG_IMPL(...) ((void)0)

#define VERIFY_IMPL1(expr) ((void)(expr))

// Brute force N-args with variadic macros.
// TODO: Is there a better way to do this?
#define VERIFY_IMPL3(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL4(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL5(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL6(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL7(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL8(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL9(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL10(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL11(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL12(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL13(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL14(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL15(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL16(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL17(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL18(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL19(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL20(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL21(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL22(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL23(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL24(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL25(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL26(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL27(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL28(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL29(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL30(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL31(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL32(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL33(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL34(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL35(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL36(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL37(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL38(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL39(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL40(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL41(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL42(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL43(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL44(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL45(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL46(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL47(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL48(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL49(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL50(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL51(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL52(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL53(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL54(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL55(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL56(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL57(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL58(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL59(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL60(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL61(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL62(expr, ...) VERIFY_IMPL1(expr)
#define VERIFY_IMPL63(expr, ...) VERIFY_IMPL1(expr)

#endif // STEINWURF_VERIFY_BACKENDS_STUB_HPP
